name: hhdelivery
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+2

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: 1.0.2
  enum_to_string: 2.2.1
  intl: 0.19.0
  flutter_dotenv: 5.2.1
  auto_route: 7.5.0
  dio: 5.8.0+1
  http: 1.4.0
  http_parser: 4.0.2
  retrofit: 4.4.2
  hive: 2.2.3
  hive_flutter: 1.1.0
  shared_preferences: 2.2.2
  flutter_hooks: 0.18.6
  hooks_riverpod: 2.3.8
  permission_handler: 11.0.1
  flutter_svg: 2.0.5
  carousel_slider: 4.2.1
  shimmer: 3.0.0
  flutter_html: 3.0.0-beta.2
  webview_flutter: 4.4.2
  flutter_native_splash: 2.4.0
  pin_code_fields: 8.0.1
  flutter_spinkit: 5.2.1
  flutter_swipe_action_cell: 3.1.5
  google_sign_in: 6.1.6
  # firebase_core: ^3.3.0
  dropdown_search: 5.0.6
  url_launcher: 6.1.11
  flutter_pdfview: 1.4.0
  path: 1.9.0
  path_provider: 2.0.14
  syncfusion_flutter_pdfviewer: 27.2.5
  cross_file: 0.3.4+2
  syncfusion_flutter_datagrid: 27.2.5
  syncfusion_flutter_core: 27.2.5
  image_picker: 1.0.4
  jwt_decode: 0.3.1
  file_picker: 8.3.2
  open_file: 3.4.0
  qr_flutter: 4.1.0
  flutter_doc_scanner: ^0.0.16
dev_dependencies:
  flutter_test:
    sdk: flutter
  auto_route_generator: 7.1.2
  build_runner: 2.3.3
  retrofit_generator: 6.0.0+3
  hive_generator: 2.0.1
  flutter_launcher_icons: 0.14.0
dependency_overrides:
  watcher: ^1.1.0
flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/
    - assets/images/
    - assets/fonts/
    - .env.development
    - .env.production
  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Black.ttf
        - asset: assets/fonts/Inter-Bold.ttf
        - asset: assets/fonts/Inter-ExtraBold.ttf
        - asset: assets/fonts/Inter-Light.ttf
        - asset: assets/fonts/Inter-Medium.ttf
        - asset: assets/fonts/Inter-Regular.ttf
        - asset: assets/fonts/Inter-SemiBold.ttf
        - asset: assets/fonts/Inter-Thin.ttf

flutter_intl:
  enabled: true
  class_name: S
  main_locale: vi
  arb_dir: lib/l10n
  output_dir: lib/generated
  use_deferred_loading: false

flutter_native_splash:
  background_image: assets/images/splash.png
  image: assets/images/logo.png
  android_12:
    image: assets/images/logo12.png
    color: "#ffffff"
  android: true
  ios: true

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/launcher_icon.png"
  min_sdk_android: 21
